# Additive Level4 integration; existing maple-w2-xmx sources/options are untouched.
set(MAPLE_L4_ROOT "${CMAKE_CURRENT_LIST_DIR}/..")
add_executable(maple-level4-contract-tests "${MAPLE_L4_ROOT}/tests/level4_contract_tests.cpp")
target_include_directories(maple-level4-contract-tests PRIVATE "${MAPLE_L4_ROOT}/include")
add_test(NAME maple-level4-contract-tests COMMAND maple-level4-contract-tests)
add_executable(maple-level4-host-tests "${MAPLE_L4_ROOT}/tests/level4_host_tests.cpp" "${MAPLE_L4_ROOT}/src/maple_level4.cpp")
target_include_directories(maple-level4-host-tests PRIVATE "${MAPLE_L4_ROOT}/tests/level4_mock" "${MAPLE_L4_ROOT}/include")
target_compile_definitions(maple-level4-host-tests PRIVATE MAPLE_LEVEL4_SCALAR_TEST=1)
add_test(NAME maple-level4-host-tests COMMAND maple-level4-host-tests)
if(MAPLE_BUILD_SYCL OR TARGET maple-w2-xmx)
    if(NOT TARGET maple-w2-xmx)
        message(FATAL_ERROR "Level4 expects the existing maple-w2-xmx target; do not replace the caller's SYCL context")
    endif()
    add_library(maple-level4 STATIC "${MAPLE_L4_ROOT}/src/maple_level4.cpp")
    target_include_directories(maple-level4 PUBLIC "${MAPLE_L4_ROOT}/include")
    target_link_libraries(maple-level4 PUBLIC maple-w2-xmx)
    target_compile_options(maple-level4 PRIVATE ${MAPLE_PRECISE_FLAGS})
    add_executable(maple-level4-probe "${MAPLE_L4_ROOT}/tools/level4_probe.cpp")
    target_link_libraries(maple-level4-probe PRIVATE maple-level4)
    target_compile_options(maple-level4-probe PRIVATE ${MAPLE_PRECISE_FLAGS})
endif()
